# System Log Viewer Icons

install_data('hicolor_apps_16x16_mate-system-log.png',
  rename: 'mate-system-log.png',
  install_dir: join_paths(datadir, 'icons/hicolor/16x16/apps')
)

install_data('hicolor_apps_22x22_mate-system-log.png',
  rename: 'mate-system-log.png',
  install_dir: join_paths(datadir, 'icons/hicolor/22x22/apps')
)

install_data('hicolor_apps_24x24_mate-system-log.png',
  rename: 'mate-system-log.png',
  install_dir: join_paths(datadir, 'icons/hicolor/24x24/apps')
)

install_data('hicolor_apps_32x32_mate-system-log.png',
  rename: 'mate-system-log.png',
  install_dir: join_paths(datadir, 'icons/hicolor/32x32/apps')
)

install_data('hicolor_apps_48x48_mate-system-log.png',
  rename: 'mate-system-log.png',
  install_dir: join_paths(datadir, 'icons/hicolor/48x48/apps')
)

install_data('hicolor_apps_256x256_mate-system-log.png',
  rename: 'mate-system-log.png',
  install_dir: join_paths(datadir, 'icons/hicolor/256x256/apps')
)

install_data('hicolor_apps_scalable_mate-system-log-symbolic.svg',
  rename: 'mate-system-log-symbolic.svg',
  install_dir: join_paths(datadir, 'icons/hicolor/scalable/apps')
)
